classdef Fix
  
  properties (Constant)
    % TODO: dt
    FLDSINFO = {
      'x' 'timeseries' false
      'y' 'timeseries' false
      'a' 'timeseries' false
      'b' 'timeseries' false
      'theta' 'timeseries' false
      'wing_anglel' 'timeseries' false
      'wing_angler' 'timeseries' false
      'firstframe' 'special' false % matches for duotrax
      'endframe' 'special' false % etc
      'nframes' 'special' false
      'off' 'special' false
      'roi' 'match' false
      'arena' 'match' false
      'moviefile' 'match' false
      'dt' 'match' false
      'timestamps' 'timeseries' false
      'wingtype' 'timeseries' false
      'xwingl' 'timeseries' false
      'ywingl' 'timeseries' false
      'xwingr' 'timeseries' false
      'ywingr' 'timeseries' false
      'x_mm' 'timeseries' false
      'y_mm' 'timeseries' false
      'theta_mm' 'timeseries' false
      'a_mm' 'timeseries' false
      'b_mm' 'timeseries' false
      'pxpermm' 'match' false
      'fps' 'match' false
      'susp' 'timeseries' false  % Optional from here on
      'xpred' 'timeseries' true
      'ypred' 'timeseries' true
      'thetapred' 'timeseries' true % Generated by suspicious_seqs etc
      'dx' 'timeseries' true
      'dy' 'timeseries' true
      'v' 'timeseries' true
      'matname' 'match' true
      };
    FLDS = cell2table(Fix.FLDSINFO,'VariableNames',{'fld','type','rm'});
    FLDS_ALLKNOWN = Fix.FLDSINFO(:,1);
    FLDS_TIMESERIESDATA = lclInitFldsTS();
    FLDS_MATCH = lclInitFldsMatch();
    FLDS_RM = lclInitFldsRm();
  end
  
end

function flds = lclInitFldsTS()
flds = Fix.FLDS.fld(strcmp(Fix.FLDS.type,'timeseries'));
end
function flds = lclInitFldsMatch()
flds = Fix.FLDS.fld(strcmp(Fix.FLDS.type,'match'));
end
function flds = lclInitFldsRm()
flds = Fix.FLDS.fld(Fix.FLDS.rm);
end
